config/routes.rb
Projects::Application.routes.draw do
  get "welcome/index"

   root 'welcome#index'
   
   get "welcome/about"
   get "welcome/contacts"
   get "welcome/projects"
   get "welcome/resume"

  Rails.application.routes.draw do 
    resources :blog do 
      resources :comments
    end
  end

  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	 
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
                    length: { minimum: 5 }



    # validates :tag, presence: true
                  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
   	# http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]	

	def index
    	@blog = Blog.all
  	end


	def show
		@blog = Blog.find(params[:id])
	end

	def new
		# @blog = Blog.new
		flash[:notice] = "Blog under construction. Coming soon!"
		redirect_to blog_index_path
	end

	def edit
  		@blog = Blog.find(params[:id])
	end

	def create
		@blog = Blog.new(blog_params)
 		if @blog.save
  			redirect_to @blog
  		else
  			render 'new'
  		end
		# redirect_to  blog_index_path
	end

	def update
  		@blog = Blog.find(params[:id])
 
		if @blog.update(blog_params)
	    	redirect_to @blog
	  	else
	    	render 'edit'
	  	end
	end

	def destroy
		@blog = Blog.find(params[:id])
		@blog.destroy
		redirect_to blog_index_path
	end

	private
	  def blog_params
	    params.require(:blog).permit(:title, :text)
	  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	# http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

	def show
		@blog = @blog = Blog.find(params[:blog_id])
		@comment = @blog.comments.find(params[:id])
	end

	def create
		@blog = Blog.find(params[:blog_id])
    	@comment = @blog.comments.create(comment_params)
    	redirect_to blog_path(@blog)
	end

	def edit
		@blog = Blog.find(params[:blog_id])
		@comment = @blog.comments.find(params[:id])
	end

	def update
		@blog = Blog.find(params[:blog_id])
		@comment = @blog.comments.find(params[:id])
		if @comment.update(comment_params)		
			redirect_to blog_path(@blog)
		else
			render 'edit_blog_comment'
		end
	end

	def destroy
		@blog = Blog.find(params[:blog_id])
		@comment = @blog.comments.find(params[:id])
		@comment.destroy
		redirect_to blog_path(@blog)
	end


	private
	    def comment_params
	      params.require(:comment).permit(:commenter, :body)
	    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
    #puts comment 
  end

  def contacts
  end

  def projects
  end

  # def blog
  # end

  def resume
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blog/edit.html.erb
<%=render file: '/app/views/layouts/title-content'%>
<h2>Edit Article</h2>

<%= form_for :blog, url: blog_path(@blog), method: :patch do |f| %>
 
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@blog.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <%= select_tag(:option, options_for_select([['', 1], ['Software Engineering', 2], 
     ['Data Science', 3], ['Ruby', 4]],   :selected => :option )) %>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit "Update" %>
  </p>
 
<% end %>

<p><b><%=link_to "Back to main page", blog_index_path%>

<%=render file: '/app/views/layouts/footer-content'%>

app/views/blog/index.html.erb
<%=render file: '/app/views/layouts/title-content'%>
 <% if flash[:notice] %>
    <div class="notice"><b><%= flash[:notice] %></b></div>
  <% end %>

	<div class="home_container">
		<div class="blog_container">
			<h2>Blogs</h2>
			<table>
			  <tr>
			    <!-- <th>Title</th> -->
			    <!-- <th>Text</th> -->
			  </tr>


			 
			  <% @blog.each do |article| %>
			    <tr>
			      <%-# <td><%= article.title </td>- %>
			      <td><%= link_to article.title, blog_path(article) %></td>
			      <td><%= link_to 'Edit', edit_blog_path(article) %></td>
			      <td><%= link_to 'Delete', blog_path(article),
			              method: :delete,
			              data: { confirm: 'Are you sure?' } %></td>
			    </tr>
			  <% end %>
			</table>
			<p><b><%=link_to "Create New Article", new_blog_path%></b></p>
		</div>
	</div>

<%=render file: '/app/views/layouts/footer-content'%>

app/views/blog/new.html.erb
<%=render file: '/app/views/layouts/title-content'%>
	<h1>Create New Article</h1>
	<div class="container">
		<%= form_for :blog, url: blog_index_path do |f| %>

		<% if @blog.errors.any? %>
		    <div id="error_explanation">
		      <h2>
		        <%= pluralize(@blog.errors.count, "error") %> prohibited
		        this article from being saved:
		      </h2>
		      <ul>
		        <% @blog.errors.full_messages.each do |msg| %>
		          <li><%= msg %></li>
		        <% end %>
		      </ul>
		    </div>
	  	<% end %>
		


		  <p>
		    <%= f.label :title  %><br>
		    <%= f.text_field :title %>
		  </p>
		 
		 <p>Tags</p>
		 <!-- <select action=f>
		 	<option></option>
		 	<option>Software Engineering</option>
		 	<option>Data Science</option>
		 	<option>Ruby</option>
		 	<option>Other</option>
		 </select> -->
		 <%= select_tag(:option, options_for_select([['', 1], ['Software Engineering', 2], 
		 ['Data Science', 3], ['Ruby', 4]],   :selected => :option )) %>



		  <p>
		    <%= f.label :text %><br>
		    <%= f.text_area :text %>
		  </p>		 

		  <p>
		    <%= f.submit "Post" %>
		  </p>
		<% end %>
	</div>

<%= link_to 'Back to Blog Main Page', blog_index_path %>

<%=render file: '/app/views/layouts/footer-content'%>

app/views/blog/show.html.erb
<%=render file: '/app/views/layouts/title-content'%>
<h2>List of Articles</h2>
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%=simple_format h @blog.text %>
  <%-# <%= @blog.text -%>
</p>

<h2>Comments</h2>
	<% @blog.comments.each do |comment| %>
		  <p>
		    <strong>Commenter:</strong>
		    <%= comment.commenter %>
		  </p>
		 
		 <!-- Partial out these -->
		  <p>
		    <strong>Comment:</strong>
		    <%= comment.body %>
		  </p>
		  <p>
		       
	         <%= link_to 'update', edit_blog_comment_path(comment.blog.id, comment.id)%>
	         <%= link_to 'Delete Comment', [comment.blog, comment],
		               method: :delete,
		               data: { confirm: 'Are you sure?' } %>
		 </p>
<% end %>



 
<h2>Add a comment:</h2>
<%= form_for([@blog, @blog.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit "Add Comment" %>
  </p>
<% end %>


<%= link_to 'Edit', edit_blog_path(@blog) %>
<%= link_to 'Back to Blog Main Page', blog_index_path %>
<%-#=render file: '/app/views/layouts/footer-content'-%>
</body>
</html>

app/views/comments/edit.html.erb
<%=render file: '/app/views/layouts/title-content'%>

<h2>update comment:</h2>
<%= form_for @comment, url: blog_comment_path(@comment.blog.id, @comment.id), method: :patch do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit "Edit Comment" %>
  </p>
<% end %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projects</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/footer-content.html.erb
<div id="footer">
<div class="navbar navbar-default navbar-fixed-bottom" role="navigation" style="background: black">
  <div class="container">
    <p class ="navbar-text col-md-12 text-center">
      Created by Wayne Morris.
      <br>Email: waynemorris75@gmail.com<br>
      ©2015 Wayne Morris. All rights reserved.
    </p>
  </div>
</div>
</div> 
<!-- Modal
<div class="modal fade" id="project1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<h4 class="modal-title" id="myModalLabel">Favorite App Page</h4>
</div>
<div class="modal-body">
<img class="img-responsive" src="http://placehold.it/1140x350">
This was my first project in this class. I learned a lot about HTML and CSS.
</div>
<div class="modal-footer">
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>
</div>
</div>
</div>
-->
</body>

</html>

app/views/layouts/nav-menu.html.erb
<html>
<head>
  <style type="text/css"></style>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <!-- Still not what it suppose to b -->



</head>


<div style="background: currentColor;">
  <div class="container" style="padding-left: 150px; padding-right: 150px">
    <div class="row">
      <div class="col-md-2" style="padding-left: 0">
        <h4>
          <%= link_to "Home", welcome_index_path %>
        </h4>
      </div>
      <div class="col-md-2"style="padding-left: 0">
        <h4>
          <%= link_to "About", welcome_about_path %>
        </h4>
      </div>
      <div class="col-md-2" style="padding-left: 0">
        <h4>
          <%= link_to "Projects", welcome_projects_path %>
        </h4>

      </div>

      <div class="col-md-2" style="padding-left: 0">
        <h4>
          <%= link_to "Resume", welcome_resume_path %>
        </h4>

      </div>
      <div class="col-md-2" style="padding-left: 0">
        <h4>
          <%= link_to "Contacts", welcome_contacts_path %>
        </h4>
      </div>
      <div class="col-md-2" style="padding-left: 0">
        <h4>
          <%= link_to "Blog", blog_path %>
        </h4>
      </div>
    </div>
  </div>
</div>

app/views/layouts/project_carousels/cns_carousel.html.erb
    <h2>Campus Naviation System</h2>
       <p>
         We developed an application using the GoogleMap API for users to conveniently navigate and locate buildings and departments on the Andrews University Campus. This was done as an academic project incorporating all the concepts and skills that go into the software development cyclSample screen shots of the application are provided below.
       </p>
      <br>
      <div id="navigationSystem" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#navigationSystem" data-slide-to="0" class="active"></li>
          <li data-target="#navigationSystem" data-slide-to="1"></li>
          <li data-target="#navigationSystem" data-slide-to="2"></li>
          <li data-target="#navigationSystem" data-slide-to="3"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">

          <div class="item active">
            <%=image_tag "project/main.jpg", alt:"Main Screen", width:"460", height:"345"%>
            <div class="carousel-caption">
              <h3>Main</h3>
              <p>Main display for the application</p>
            </div>
          </div>

          <div class="item">
            <%=image_tag "project/tracking.jpg", alt:"Tracking Feature", width:"460", height:"345"%>
            <div class="carousel-caption">
              <h3>Tracking Feature</h3>
              <p>Tracking options for users</p>
            </div>
          </div>

          <div class="item">
            <%=image_tag "project/view_submenu.png", alt:"Submenu View", width:"460", height:"345"%>
            <div class="carousel-caption">
              <h3>Submenu View</h3>
              <p>View options for users</p>
            </div>
          </div>

          <div class="item">
            <%=image_tag  "project/view_submenu_options.png", alt:"Submenu Options", width:"460", height:"345"%>
            <div class="carousel-caption">
              <h3>Sub Menu Options</h3>
              <p>Sub-menu options displaying additional options for the general view</p>
            </div>
          </div>

        <div class="item">
          <%=image_tag  "project/running_ad.png", alt:"Running Ad", width:"460", height:"345"%>
          <div class="carousel-caption">
            <h3>Running Advertisement</h3>
            <p>Running advertisements for the school</p>
          </div>
        </div>
       </div> 
        <!-- Left and right controls -->
          <a class="left carousel-control" href="#navigationSystem" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#navigationSystem" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
    </div>
  <br>

app/views/layouts/project_carousels/eia_carousel.html.erb
<h2>Environmental and Engineering Consulting</h2>
  <p>
     I have worked on several environmental and engineering projects, some of which I was project manager and project team lead. I have successfully worked with a number of international organizations who are world-leaders in their trade. These projects include: preparation of Environmental Impact Assessment, Closure Plans, Due Diligence Audit, Chemical Plant Assessment and Monitoring Reports. Some projects are shown below.
  </p>
	<div id="myCarousel" class="carousel slide" >
	  <div class="carousel-inner" role="listbox">
	       <div class="item active">
		       <a href="http://www.nepa.gov.jm/eias/StAnn/Golden%20Sands%20Beach%20Cottages/FINAL_EIA_REPORT_ASN_NOV._10_10.pdf" target="_blank">       
		        	<%=image_tag "project/eia_images/EIA_Alcatel.jpg", alt:"Main Screen", width:"460", height:"345"%>
		        </a>
	        <div class="carousel-caption">
	        </div>
	      </div>

	      <div class="item">
	        <a href= "http://www.nepa.gov.jm/eias/clarendon/rocky_point/stock-pile/revised_rinker_port_eia.pdf" target="_blank">	        
	            <%=image_tag "project/eia_images/EIA_Cemex.jpg", class:"img-responsive center-block", alt:"Tracking Feature", width:"460", height:"345"%>
	            <div class="carousel-caption">
	            </div>
	        </a>
	      </div>

	      <div class="item">
	        <a href="http://www.nepa.gov.jm/new/services_products/applications/eias/docs/misc/FibraLink/New-Cable-Lay/Fibralink_New_Cable_Lay-Marine_Assessment_Report-FINAL.pdf" target="_blank">
	            <%=image_tag "project/eia_images/EIA_FibraLink.jpg", alt:"Submenu View", width:"460", height:"345"%>
	        </a>
	            <div class="carousel-caption">
	            </div>	        
	      </div>

	      <div class="item">
	      	<a href="http://www.nepa.gov.jm/eias/Clarendon/Jamalco/run_off_storage/EIS%20Report%20Final%20Version.pdf" target="_blank">
	        	<%=image_tag  "project/eia_images/EIA_Jamalco.jpg", alt:"Submenu Options", width:"460", height:"345"%>
	        </a>
	        <div class="carousel-caption">
	        </div>
	      </div>

	      <div class="item">
	      	<a href="http://www.nepa.gov.jm/eias/trelawny/martha-brae/holland_estate/holland_estate_eia.pdf" target="_blank">
	        	<%=image_tag  "project/eia_images/EIA_Kencasa.jpg", alt:"Running Ad", width:"460", height:"345"%>
	        </a>
	        <div class="carousel-caption">
	        </div>
	      </div>

	      <div class="item">
	      	<a href="http://www.nepa.gov.jm/new/services_products/applications/eias/docs/Clarendon/Rocky_Point/Stock-pile/eia_for_port_&_transportation_corridor_-_volume_i.pdf" target="_blank">
	        	<%=image_tag  "project/eia_images/EIA_Rinker.jpg", alt:"Geotracking", width:"460", height:"345"%>
	        </a>
	        <div class="carousel-caption">
	         
	        </div>
	      </div>

	      <div class="item">
	      <a href="http://www.nepa.gov.jm/eias/Manchester/Kirkvine/Windalco.pdf" target="_blank">
	        	<%=image_tag  "project/eia_images/EIA_Windalco.jpg", alt:"path", width:"460", height:"345"%>
	       </a>
	        <div class="carousel-caption">
	         
	        </div>
	      </div>
	  </div> 

	  <a class="left carousel-control" href="#myCarousel" data-slide="prev" role="button">
	          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true">
	          </span> 
	        <span class="sr-only">Next</span>
	  </a>

	    <a
	    class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
	        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true">
	        </span> 
	        <span class="sr-only">Next</span>
	    </a>
	</div>


app/views/layouts/project_carousels/header_carousel.html.erb
<%=render file: '/app/views/layouts/title-content'%>

<title>Projects</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width">
  <!--<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

  <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js' %>
  <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <%= stylesheet_link_tag "application", media: "all" %>
  <style>
      .carousel-inner > .item > img,
      .carousel-inner > .item > a > img {
          width: 70%;
          margin: auto;
      }
  </style>


<style type="text/css"></style>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

</head>

app/views/layouts/project_carousels/thesis_carousel.html.erb
    <br>
    <h2>Thesis</h2>
   <p>
      This project details the proposal of a mathematical model using Discrete Time Markov's Chain (DTMC) to determine software reliability based on the reliability of individual software components within a system. The proposed model takes into consideration the heterogeneity of the different software systems, which includes: Batch-Sequential/Pipeline Architectural Style, Parellel-Pipe style, Fault Tolerance and Call and Return Architecture style.Each architectural style was mathematically modelled for which the DTMC was applied to each software system components based on its architectural style to determine reliability of the overall software system
    </p>
  <div id="thesis" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#thesis" data-slide-to="0" class="active"></li>
      <li data-target="#thesis" data-slide-to="1"></li>
      <li data-target="#thesis" data-slide-to="2"></li>
      <li data-target="#thesis" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

      <div class="item active">
        <%=image_tag "project/thesis/abstract_pg_1.png", alt:"Abstract Page 1", width:"460", height:"345"%>
        <div class="carousel-caption">
        </div>
      </div>

      <div class="item">
        <%=image_tag "project/thesis/abstract_pg_2.png", alt:"Abstract Page 2", width:"460", height:"345"%>
        <div class="carousel-caption">
         
        </div>
      </div>

      <div class="item">
        <%=image_tag "project/thesis/abstract_pg_3.png", alt:"Abstract Page 3", width:"460", height:"345"%>
        <div class="carousel-caption">
        </div>
      </div>

      <div class="item">
        <%=image_tag  "project/thesis/abstract_pg_4.png", alt:"Abstract Page 4", width:"460", height:"345"%>
        <div class="carousel-caption">
        </div>
      </div>

      <div class="item">
        <%=image_tag  "project/thesis/intro_pg_1.png", alt:"Intro first page", width:"460", height:"345"%>
        <div class="carousel-caption">
        </div>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#thesis" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#thesis" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <br>

app/views/layouts/title-content.html.erb
<html>
<head>

  <style type="text/css"></style>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width">

</head>
<body style="background:#FFE;">
<div class="main-title">
  <div class="container" style="padding-left: 150px; padding-right: 150px">
    <div class="row">
      <h1>Wayne Morris</h1>
    </div>
    <div class="row">
      <h1 style="text-shadow: 2px 2px #FF0000; font-size:30px"; >"Positively Impacting Lives through Science and Engineering"</h1>
    </div>
  </div>
 </div>

    <div style="background: currentColor;">
      <div class="container" style="padding-left: 150px; padding-right: 150px">
        <div class="row">
          <div class="col-md-2" style="padding-left: 0">
            <h4>
              <%= link_to "Home", welcome_index_path %>
            </h4>
          </div>
          <div class="col-md-2"style="padding-left: 0">
            <h4>
              <%= link_to "About", welcome_about_path %>
            </h4>
          </div>
          <div class="col-md-2" style="padding-left: 0">
            <h4>
              <%= link_to "Projects", welcome_projects_path %>
            </h4>

          </div>

          <div class="col-md-2" style="padding-left: 0">
            <h4>
              <%= link_to "Resume", welcome_resume_path %>
            </h4>

          </div>
          <div class="col-md-2" style="padding-left: 0">
            <h4>
              <%= link_to "Contact", welcome_contacts_path %>
            </h4>
          </div>
          <div class="col-md-2" style="padding-left: 0">
            <h4>
              <%= link_to "Blog", blog_index_path %>
            </h4>
          </div>
        </div>
      </div>
    </div>

app/views/welcome/resume.html.erb
<!DOCTYPE html>
<head>
  <!-- This tells the browser how to read the document. -->
  <meta charset="utf-8">

  <!-- Tells the browser what the title of this page should be. -->
  <title>Resume</title>
  <!-- <link href = "/vendor/assets/stylesheets"> -->
  <%= javascript_include_tag 'jQuery', :type => "text/javascript"%>
  <%= javascript_include_tag 'resume/helper', :type => "text/javascript" %>
  <%= javascript_include_tag 'http://maps.googleapis.com/maps/api/js?libraries=places', :type => "text/javascript"%>
  

  <meta name="viewport" content="width=device-width">
</head>

    <body unresolved>
        <div id="main">
          <div id="header" class="center-content clearfix">
            <ul id="topContacts" class='flex-box'></ul>
          </div>
          <div style='clear: both;'></div>

          <form style="background-color:#F3F3F3; text-align:right"><INPUT Type="button" VALUE="Back" onClick="history.go(-1);return true;"></form>
          
          <div id="workExperience" class='gray'>
            <h2>Work Experience</h2>
          </div>

          <div id="projects">
             <h2>
                 <%= link_to "Projects - Click here", welcome_projects_path, {:style=>'color:#999999;'} %>
            </h2>
          </div>
          <div id="education" class='gray'>
            <h2>Education</h2>
          </div>
          <div id="certifications">
            <h2>Extra Courses and Professional Development</h2>
          </div>
          <div id="mapDiv">
            <h2>Where I've Lived and Worked</h2>
          </div>
          <div id="letsConnect" class='dark-gray'>
            <h2 class='orange center-text'><%= link_to  "Let's Connect", welcome_contacts_path %></h2>
            <ul id="footerContacts" class="flex-box">
            </ul>
          </div>
        </div>

        <%= javascript_include_tag 'resume/resumeBuilder' %>


        <script type="text/javascript">
            if (document.getElementsByClassName('flex-item').length === 0) {
                // document.getElementById('topContacts').style.display = 'none';
                document.getElementById('topContacts').style.display = 'black';
            }
            if (document.getElementsByTagName('h1').length === 0) {
                // document.getElementById('header').style.display = 'none';
                document.getElementById('header').style.display = 'black';
            }
            if (document.getElementsByClassName('work-entry').length === 0) {
                // document.getElementById('workExperience').style.display = 'none';
                document.getElementById('workExperience').style.display = 'black';
            }
            if (document.getElementsByClassName('project-entry').length === 0) {
                // document.getElementById('projects').style.display = 'none';
                document.getElementById('projects').style.display = 'black';
            }
            if (document.getElementsByClassName('education-entry').length === 0) {
                // document.getElementById('education').style.display = 'none';
                document.getElementById('projects').style.display = 'black';
            }
             if (document.getElementsByClassName('certifications-entry').length === 0) {
                // document.getElementById('education').style.display = 'none';
                document.getElementById('certifications').style.display = 'black';
            }
            if (document.getElementsByClassName('flex-item').length === 0) {
                // document.getElementById('letsConnect').style.display = 'none';
                document.getElementById('letsConnect').style.display = 'black';
            }
            if (document.getElementById('map') === null) {
                // document.getElementById('mapDiv').style.display = 'none';
                document.getElementById('mapDiv').style.display = 'black';
            }
        </script>

<footer>
<center>
     <p style="background:black; color:#777; font-size:14px">
      Created by Wayne Morris.
      <br>Email: waynemorris75@gmail.com<br>
      ©2015 Wayne Morris. All rights reserved.
    </p>
</center>
</footer>